global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: postgres-exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'pgcat'
    static_configs:
      - targets: ['pgcat:9930']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']