{
 "title": "Monitoring",
 "time": { "from": "2024-09-28T11:13:42.119Z", "to": "2024-09-28T11:43:42.119Z" },
 "templating": {
  "list": [
   { "name": "nodex", "label": "Host", "query": "node-exporter:9100" },
   { "name": "job", "label": "Job", "query": "node-exporter" }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"nice\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"softirq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"steal\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\",job=\"node-exporter\"}) by (cpu)))",
     "legendFormat": "Idle - Waiting for something to happen"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_Buffers_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_Cached_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_Slab_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_PageTables_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_SwapCached_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=\"node-exporter:9100\",job=\"node-exporter\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"node-exporter:9100\", job=\"node-exporter\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"node-exporter:9100\", job=\"node-exporter\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"node-exporter:9100\", job=\"node-exporter\", device=~\"[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Max connections",
   "type": "stat",
   "description": "Determines the maximum number of concurrent connections to the database server.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"postgres-exporter:9187\"}"
    }
   ]
  },
  {
   "title": "Max worker processes",
   "type": "stat",
   "description": "Sets the maximum number of background processes that the cluster can support. ",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=\"postgres-exporter:9187\"}"
    }
   ]
  },
  {
   "title": "Max parallel workers",
   "type": "stat",
   "description": "Sets the maximum number of workers that can be started by a single Gather or Gather Merge node. ",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{instance=\"postgres-exporter:9187\"}"
    }
   ]
  },
  {
   "title": "Effective cache",
   "type": "stat",
   "description": "Sets the planner's assumption about the effective size of the disk cache that is available to a single query.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"postgres-exporter:9187\"}"
    }
   ]
  },
  {
   "title": "Shared buffers",
   "type": "stat",
   "description": "Sets the amount of memory the database server uses for shared memory buffers. ",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"postgres-exporter:9187\"}"
    }
   ]
  },
  {
   "title": "Work mem",
   "type": "stat",
   "description": "Sets the base maximum amount of memory to be used by a query operation (such as a sort or hash table) before writing to temporary disk files.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maintenance work mem",
   "type": "stat",
   "description": "Specifies the maximum amount of memory to be used by maintenance operations, such as VACUUM, CREATE INDEX, and ALTER TABLE ADD FOREIGN KEY. ",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL buffers",
   "type": "stat",
   "description": "AL the writer sleeps for the length of time given by wal_writer_delay, unless woken up sooner by an asynchronously committing transaction.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_wal_buffers_bytes{instance=\"postgres-exporter:9187\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "description": "Shows the cache hit rate for the database.\npg_stat_database_blks_hit - Number of blocks read directly from the cache\npg_stat_database_blks_read - Number of blocks read directly from disk",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=~\"example\"} / (pg_stat_database_blks_read{datname=~\"example\"} + pg_stat_database_blks_hit{datname=~\"example\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Connections and activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "The pg_stat_activity view will have one row per server process, showing information related to the current activity of that proces",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{state=\"active\", datname=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": " Number of transaction commits",
   "type": "timeseries",
   "description": "Number of transactions in this database that have been committed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{datname=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of transaction rollbacks",
   "type": "timeseries",
   "description": "Number of transactions in this database that have been rolled back.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "pg_stat_database_xact_rollback{datname=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Buffers checkpoint total",
   "type": "timeseries",
   "description": "Number of buffers written during checkpoints.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "pg_stat_bgwriter_buffers_checkpoint_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Vacuum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Autovacuum execution count",
   "type": "timeseries",
   "description": "Number of times this table has been vacuumed by the autovacuum daemon.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "\tpg_stat_all_tables_autovacuum_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Vacuum execution count",
   "type": "timeseries",
   "description": "Number of times this table has been manually vacuumed (not counting VACUUM FULL).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "pg_stat_all_tables_vacuum_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of dead tuples in table",
   "type": "timeseries",
   "description": "Estimated number of dead rows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    { "expr": "pg_stat_all_tables_n_dead_tup", "legendFormat": "__auto" }
   ]
  },
  { "title": "Lock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Lock count",
   "type": "timeseries",
   "description": "Number of locks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PgCat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "Current number of connections for this database.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "pgcat_databases_current_connections{database=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool size",
   "type": "timeseries",
   "description": "Maximum number of server connections.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 80 },
   "targets": [
    {
     "expr": "pgcat_databases_pool_size{database=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average errors",
   "type": "timeseries",
   "description": "Average number of errors every 15 seconds.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "pgcat_stats_avg_errors{database=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average wait time",
   "type": "timeseries",
   "description": "Average of total_wait_time every 15 seconds.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 80 },
   "targets": [
    {
     "expr": "pgcat_stats_avg_wait_time{database=\"example\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active clients",
   "type": "timeseries",
   "description": "How many clients are actively communicating with a server.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "targets": [
    { "expr": "pgcat_pools_cl_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waiting clients",
   "type": "timeseries",
   "description": "How many clients are waiting for a connection from the pool.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "targets": [
    { "expr": "pgcat_pools_cl_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Idle clients",
   "type": "timeseries",
   "description": "How many clients are idle.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "targets": [
    { "expr": "pgcat_pools_cl_idle", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active server connections",
   "type": "timeseries",
   "description": "How many server connections are actively communicating with a client.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "targets": [
    { "expr": "pgcat_pools_sv_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Idle server connections",
   "type": "timeseries",
   "description": "How many server connections are idle.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "targets": [
    { "expr": "pgcat_pools_sv_idle", "legendFormat": "__auto" }
   ]
  }
 ]
}